### ISSUE TITLE
Cannot connect to localhost:8545

### ISSUE THREAD

**Issue by pikonha** [OffchainLabs/nitro-testnode#83]
After pulling the latest changes to the `release` branch, I can no longer run the node locally. This is the error I get:

```shell
index.js wait-for-sync

wait for rpc to sync

Options:
  --version            Show version number                             [boolean]
  --redisUrl                            [string] [default: "redis://redis:6379"]
  --l1url                                   [string] [default: "ws://geth:8546"]
  --l2url                              [string] [default: "ws://sequencer:8548"]
  --l3url                                 [string] [default: "ws://l3node:3348"]
  --validationNodeUrl            [string] [default: "ws://validation_node:8549"]
  --l2owner     [string] [default: "0x3f1Eae7D46d88F08fc2F8ed27FCb2AB183EB2d0E"]
  --times              times to repeat per thread          [number] [default: 1]
  --delay              delay between repeats (ms)          [number] [default: 0]
  --threads                                                [number] [default: 1]
  --threadId           first thread-Id used                [number] [default: 0]
  --serial             do all actions serially (e.g. when from is identical for
                       all threads)                   [boolean] [default: false]
  --help               Show help                                       [boolean]
  --url                url to send rpc call
                                     [string] [default: "http://sequencer:8547"]

Error: missing response (requestBody="{\"method\":\"eth_syncing\",\"params\":[],\"id\":42,\"jsonrpc\":\"2.0\"}", requestMethod="POST", serverError={"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"172.28.0.2","port":8545}, url="http://geth:8545", code=SERVER_ERROR, version=web/5.6.0)
    at Logger.makeError (/workspace/node_modules/@ethersproject/logger/lib/index.js:233:21)
    at Logger.throwError (/workspace/node_modules/@ethersproject/logger/lib/index.js:242:20)
    at /workspace/node_modules/@ethersproject/web/lib/index.js:252:36
    at step (/workspace/node_modules/@ethersproject/web/lib/index.js:33:23)
    at Object.throw (/workspace/node_modules/@ethersproject/web/lib/index.js:14:53)
    at rejected (/workspace/node_modules/@ethersproject/web/lib/index.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  reason: 'missing response',
  code: 'SERVER_ERROR',
  requestBody: '{"method":"eth_syncing","params":[],"id":42,"jsonrpc":"2.0"}',
  requestMethod: 'POST',
  serverError: Error: connect ECONNREFUSED 172.28.0.2:8545
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '172.28.0.2',
    port: 8545
  },
  url: 'http://geth:8545'
}
```

**Comment by pikonha** [comment]
fixed after running `docker system prune` 🤙🏼
